language: php
php:
- nightly
- 7.1
- 7.0
- 5.6
- 5.5
matrix:
  allow_failures:
    - php: nightly
before_install:
  - cp config/database{.default,}.php
  - cp config/auth{.default,}.php
  - cp config/email{.default,}.php
  - cp config/recording{.default,}.php
install: composer install
script:
  - composer test
after_success:
  - travis_retry php vendor/bin/coveralls -v