language: php
php:
- nightly
- 7.1
- 7.0
- 5.6
- 5.5
matrix:
  allow_failures:
    - php: nightly
install: composer install
script:
  - composer test
after_success:
  - travis_retry php vendor/bin/coveralls -v