version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: cp config/database{.default,}.php
      - run: cp config/auth{.default,}.php
      - run: cp config/email{.default,}.php
      - run: cp config/recording{.default,}.php
      - run: composer test
      - run: php vendor/bin/coveralls -v